login_notification.type.*:
  type: config_entity
  label: Login notification type
  mapping:
    id:
      type: string
      label: Login notification machine-name
    label:
      type: string
      label: Login notifcaiton human readable label
    type:
      type: string
      label: Login notificaiton type
    message:
      type: text
      label: Login notification message
    conditions:
      type: sequence
      label: Login notificaiton conditions
      sequence:
        type: mapping
        label: Login notificaiton condition
        mapping:
          configuration:
            type: sequence
            label: Condition configuration
    conditions_met_all:
      type: boolean
      label: Conditions all pass
